import { ArrowLeft, CheckCircle2, FileText, Sparkles } from 'lucide-react'
import type { PolicyFile, Screen, Tone } from '../types'
import { Badge, Button, Metric, PageHeader, Panel } from '../components/ui'

const clauses: Array<{ id: string; title: string; policy: string; context: string[]; outcome: string; tone: Tone; actions: string[]; confidence: string }> = [
  { id: '4.2', title: 'Customer Data Protection', policy: 'Customer personal information must not be shared with public AI tools.', context: ['Data: Customer Personal Data', 'AI tool: Public AI', 'Department scope: All departments'], outcome: 'BLOCK', tone: 'danger', actions: ['Block the request', 'Notify the employee', 'Record the incident', 'Recommend an approved enterprise AI'], confidence: '96%' },
  { id: '7.3', title: 'AI-Assisted Recruitment', policy: 'AI-assisted hiring decisions require approval from an HR manager.', context: ['Department: Human Resources', 'Purpose: Candidate Selection', 'Consequence: Employment decision'], outcome: 'HUMAN REVIEW', tone: 'warning', actions: ['Allow analysis', 'Prevent automatic final decision', 'Assign an authorized HR reviewer', 'Create a Decision Capsule'], confidence: '94%' },
  { id: '9.1', title: 'Approved AI Models', policy: 'Source code may only be processed by approved enterprise AI models.', context: ['Data: Source Code', 'AI tool: Approved Enterprise AI', 'Department: Engineering'], outcome: 'ALLOW AND RECORD', tone: 'success', actions: ['Allow the request', 'Record the model and user', 'Preserve the policy version', 'Create an audit event'], confidence: '93%' },
]

function formatFileSize(bytes: number) {
  if (bytes < 1024 * 1024) return `${Math.max(1, Math.round(bytes / 1024))} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

export function PolicyAnalysis({ policyFile, policyAnalysisComplete, navigate }: { policyFile: PolicyFile | null; policyAnalysisComplete: boolean; navigate: (screen: Screen) => void }) {
  if (!policyFile || !policyAnalysisComplete) return <div className="page-stack"><PageHeader eyebrow="Policy analysis" title="No policy analysis available" description="Upload and analyse a policy document before reviewing representative findings." /><Panel><div className="locked-empty"><FileText size={27} /><h2>No policy analysis available</h2><p>This frontend prototype has no completed policy analysis to review.</p><Button onClick={() => navigate('policies')} icon={<ArrowLeft size={16} />}>Back to Policy Upload</Button></div></Panel></div>

  return (
    <div className="page-stack policy-details-page">
      <PageHeader eyebrow="Policy analysis · PLY-014" title="Policy analysis details" description="Review representative findings and proposed runtime controls before applying them to agents." actions={<Badge tone="violet" dot>Simulated analysis · Representative prototype results</Badge>} />
      <Panel title="Uploaded policy" description="Metadata retained in this frontend session only." action={<Badge tone="success" dot>Analysis complete</Badge>}><div className="policy-metadata"><div><FileText size={18} /><span><small>File name</small><strong>{policyFile.name}</strong></span></div><div><small>File size</small><strong>{formatFileSize(policyFile.size)}</strong></div><div><small>File type</small><strong>{policyFile.type}</strong></div><div><small>Analysis status</small><Badge tone="success">Complete</Badge></div></div></Panel>
      <div className="metric-grid policy-metrics"><Metric label="Clauses detected" value="12" detail="Representative extraction" tone="info" /><Metric label="Automatic controls" value="8" detail="Draft runtime controls" tone="success" /><Metric label="Human-review controls" value="3" detail="Require authorization" tone="warning" /><Metric label="Policy ambiguities" value="1" detail="Awaiting confirmation" tone="danger" /></div>
      <div className="policy-clause-stack">{clauses.map((clause) => <Panel key={clause.id} className="policy-clause-card" title={`Clause ${clause.id} — ${clause.title}`} action={<Badge tone={clause.tone}>{clause.outcome}</Badge>}><div className="policy-clause-grid"><section><span className="section-label">Original policy text</span><blockquote>“{clause.policy}”</blockquote><span className="section-label">Source evidence</span><p className="policy-evidence"><FileText size={14} /> Uploaded policy · Clause {clause.id}</p></section><section><span className="section-label">Detected context</span><div className="policy-context-list">{clause.context.map((item) => <span key={item}>{item}</span>)}</div><span className="section-label">Generated control</span><Badge tone={clause.tone}>{clause.outcome}</Badge></section><section><span className="section-label">Runtime actions</span><ul className="policy-runtime-actions">{clause.actions.map((action) => <li key={action}><CheckCircle2 size={14} />{action}</li>)}</ul><div className="policy-confidence"><span>Confidence</span><strong>{clause.confidence}</strong></div></section></div></Panel>)}</div>
      <Panel title="Policy ambiguity" description="Administrator confirmation is required before this wording can be applied consistently." action={<Badge tone="warning" dot>Awaiting administrator confirmation</Badge>}><div className="policy-ambiguity"><div><span className="section-label">Original policy</span><blockquote>“Sensitive information should be handled carefully.”</blockquote><span className="section-label">Question</span><h3>What should be classified as sensitive information?</h3></div><div className="policy-ambiguity-options">{['Customer names', 'Phone numbers', 'Financial records', 'Source code', 'Employee salaries'].map((option) => <div key={option}><span />{option}</div>)}</div></div></Panel>
      <div className="policy-details-actions"><Button variant="secondary" onClick={() => navigate('policies')} icon={<ArrowLeft size={16} />}>Back to Policy Upload</Button><Button onClick={() => navigate('agents')} icon={<Sparkles size={16} />}>Continue to Agents</Button></div>
    </div>
  )
}
